<Project>
  <PropertyGroup>
    <AcceptAndroidSDKLicenses>true</AcceptAndroidSDKLicenses>
  </PropertyGroup>
  <PropertyGroup Condition="'$(TargetFramework)' == 'net8.0-android'">
    <AndroidKeyStore>true</AndroidKeyStore>
    <AndroidSigningKeyStore>$(MSBuildProjectDirectory)/labyItems.keystore</AndroidSigningKeyStore>
    <AndroidSigningKeyAlias Condition="'$(AndroidSigningKeyAlias)' == ''">labyItemsSigningKey</AndroidSigningKeyAlias>
  </PropertyGroup>
</Project>
