using System.Collections.ObjectModel; using System.ComponentModel; using System.Runtime.CompilerServices; using System.Text.Json; using labyItems.Models.Enums; using labyItems.Services;
namespace labyItems.Pages.NonStandard;
public partial class EvocationCombatEditorPage:ContentPage,INotifyPropertyChanged{
 readonly TaskCompletionSource<DruidEvocationService.EvocRaw?> done=new(); readonly DruidEvocationService.EvocRaw draft; string message=""; string? effect,damageType,armourType; public new event PropertyChangedEventHandler? PropertyChanged;
 EvocationCombatEditorPage(DruidEvocationService.EvocRaw source,bool damage){draft=Clone(source);IsDamage=damage;Title=damage?"Configure damage":"Configure healing";foreach(var p in damage?draft.GetDamageAmounts():draft.GetHealAmounts())AmountRows.Add(new(p));SelectedEffectType=(damage?draft.GetDamageTypes():draft.GetHealTypes()).FirstOrDefault();SelectedDamageType=draft.GetDamageCategories().FirstOrDefault().ToDisplayText();foreach(var p in draft.GetArmourApplies())ArmourRows.Add(new(p));SelectedArmourType=draft.GetArmourType();AmountRows.CollectionChanged+=(_,_)=>Changed();ArmourRows.CollectionChanged+=(_,_)=>Changed();InitializeComponent();BindingContext=this;}
 public bool IsDamage{get;} public new string Title{get;} public ObservableCollection<CombatPairRow> AmountRows{get;}=[];public ObservableCollection<CombatPairRow> ArmourRows{get;}=[];public IReadOnlyList<string> EffectTypes{get;}=Enum.GetNames<DamType>();public IReadOnlyList<string> DamageTypes{get;}=Enum.GetValues<DamageTypeEnum>().Where(x=>x!=DamageTypeEnum.Unknown).Select(x=>x.ToDisplayText()).ToList();public IReadOnlyList<string> ArmourTypes{get;}=Enum.GetNames<ArmourType>();public bool HasAmounts=>AmountRows.Count>0;public bool CanAddArmour=>IsDamage&&ArmourRows.Count<AmountRows.Count;
 public string? SelectedEffectType{get=>effect;set{effect=value;Raise();}}public string? SelectedDamageType{get=>damageType;set{damageType=value;Raise();}}public string? SelectedArmourType{get=>armourType;set{armourType=value;Raise();}}public string ValidationMessage{get=>message;set{message=value;Raise();Raise(nameof(HasValidationMessage));}}public bool HasValidationMessage=>message.Length>0;
 public static async Task<DruidEvocationService.EvocRaw?> EditAsync(INavigation nav,DruidEvocationService.EvocRaw source,bool isDamage){var p=new EvocationCombatEditorPage(source,isDamage);await nav.PushModalAsync(p);return await p.done.Task;}void Changed(){while(ArmourRows.Count>AmountRows.Count)ArmourRows.RemoveAt(ArmourRows.Count-1);Raise(nameof(HasAmounts));Raise(nameof(CanAddArmour));}void OnAddAmountClicked(object? s,EventArgs e)=>AmountRows.Add(new());void OnRemoveAmountClicked(object? s,EventArgs e){if((s as Button)?.CommandParameter is CombatPairRow r)AmountRows.Remove(r);}void OnAddArmourClicked(object? s,EventArgs e){if(CanAddArmour)ArmourRows.Add(new());}void OnRemoveArmourClicked(object? s,EventArgs e){if((s as Button)?.CommandParameter is CombatPairRow r)ArmourRows.Remove(r);}async void OnCancelClicked(object? s,EventArgs e){done.TrySetResult(null);await Navigation.PopModalAsync();}
 protected override bool OnBackButtonPressed(){done.TrySetResult(null);return base.OnBackButtonPressed();}protected override void OnDisappearing(){base.OnDisappearing();done.TrySetResult(null);}
 async void OnApplyClicked(object? s,EventArgs e){if(!Pairs(AmountRows,out var amounts,"amount")||!Pairs(ArmourRows,out var armour,"armour applies"))return;if(amounts.Count>0&&string.IsNullOrWhiteSpace(effect)){ValidationMessage="Choose a type when an amount is present.";return;}if(IsDamage&&amounts.Count>0&&string.IsNullOrWhiteSpace(damageType)){ValidationMessage="Choose a damage type when an amount is present.";return;}if(IsDamage&&armour.Count>0&&string.IsNullOrWhiteSpace(armourType)){ValidationMessage="Choose an armour type when armour applies is present.";return;}if(IsDamage){var cat=ParseDamage(damageType);draft.Damage=amounts.Count==0&&armour.Count==0?null:new(){amount=amounts,type=Repeat(effect,amounts.Count),DamageType=Enumerable.Repeat(cat,amounts.Count).ToList(),ArmourApplies=armour,ArmourType=armourType??""};draft.damage=null;draft.damType=null;draft.InnatePacApplies=null;}else{draft.Heal=amounts.Count==0?null:new(){amount=amounts,type=Repeat(effect,amounts.Count)};draft.healing=null;draft.healType=null;}done.TrySetResult(draft);await Navigation.PopModalAsync();}
 bool Pairs(IEnumerable<CombatPairRow> rows,out List<int[]> result,string label){result=[];foreach(var r in rows){if(!int.TryParse(r.TblpText,out var a)||!int.TryParse(r.LocText,out var b)){ValidationMessage=$"Complete both TBLP and LOC for every {label} row.";return false;}result.Add([Math.Max(0,a),Math.Max(0,b)]);}return true;}static List<string> Repeat(string? x,int n)=>Enumerable.Repeat(x??"",n).ToList();static DamageTypeEnum ParseDamage(string? x){var k=new string((x??"").Where(char.IsLetterOrDigit).ToArray());return Enum.TryParse<DamageTypeEnum>(k,true,out var v)?v:DamageTypeEnum.Unknown;}static DruidEvocationService.EvocRaw Clone(DruidEvocationService.EvocRaw x)=>JsonSerializer.Deserialize<DruidEvocationService.EvocRaw>(JsonSerializer.Serialize(x))??new();void Raise([CallerMemberName]string? n=null)=>PropertyChanged?.Invoke(this,new(n));}
public sealed class CombatPairRow:INotifyPropertyChanged{string tblp="",loc="";public CombatPairRow(){}public CombatPairRow(int[] p){tblp=p.ElementAtOrDefault(0).ToString();loc=p.ElementAtOrDefault(1).ToString();}public event PropertyChangedEventHandler? PropertyChanged;public string TblpText{get=>tblp;set{tblp=value;PropertyChanged?.Invoke(this,new(nameof(TblpText)));}}public string LocText{get=>loc;set{loc=value;PropertyChanged?.Invoke(this,new(nameof(LocText)));}}}
