<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="FluentMigrator" />
        <PackageReference Include="FluentMigrator.Runner" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Data.SqlClient" />
        <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" />
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
        <PackageReference Include="System.Drawing.Common" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="..\..\labyItems\Resources\Raw\druids_way\evocs.json" Link="Resources/Raw/druids_way/evocs.json" />
        <EmbeddedResource Include="..\..\labyItems\Resources\Raw\words_from_above\miracles.json" Link="Resources/Raw/words_from_above/miracles.json" />
        <EmbeddedResource Include="..\..\labyItems\Resources\Raw\grimoire\allSpells.json" Link="Resources/Raw/grimoire/allSpells.json" />
        <EmbeddedResource Include="..\..\labyItems\Resources\Raw\makes_abilities.json" Link="Resources/Raw/makes_abilities.json" />
        <EmbeddedResource Include="..\..\labyItems\Resources\Raw\evolution_classes\merged.json" Link="Resources/Raw/evolution_classes/merged.json" />
        <EmbeddedResource Include="..\..\labyItems\Resources\Raw\people\classes.json" Link="Resources/Raw/people/classes.json" />
        <EmbeddedResource Include="..\..\labyItems\Resources\Raw\people\people.json" Link="Resources/Raw/people/people.json" />
        <EmbeddedResource Include="..\..\labyItems\Resources\Raw\people\lifescales.json" Link="Resources/Raw/people/lifescales.json" />
    </ItemGroup>
</Project>
